name: Report ATDD tests

on:
  # Ejecutar en el evento workflow_dispatch y en las ramas main y ATDD
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requeriments.txt

      - name: Download ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip

      - name: Set Permissions for ChromeDriver
        run: |
          chmod +x chromedriver-linux64

      - name: Run Test
        if: always()
        run: behave -f allure_behave.formatter:AllureFormatter -o reports -vv features
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1
        if: always()
        with:
          allure_results: reports
          allure_history: reports

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: reports
